
export const translations = {
  ru: {
    title: 'Инжиниринговая компания',
    header: {
      services: 'Услуги',
      contact: 'Связаться с нами',
    },
    nav: [
      { name: 'Главная', href: '#' },
      { name: 'О компании', href: '#' },
      { name: 'Блог / Кейсы', href: '#' },
    ],
    hero: {
      title: 'Комплексный инжиниринг и проектирование',
      subtitle: 'Мы предоставляем полный спектр услуг: от разработки концепции до авторского надзора и сдачи объекта в эксплуатацию.',
      button: 'Начать проект',
    },
    services: {
      sectionTitle: 'Наши Услуги',
      title: 'Полный цикл инжиниринговых услуг',
      subtitle: 'Мы предлагаем комплексные решения для всех этапов реализации вашего проекта.',
      serviceNames: [
        'Инжиниринг',
        'Проектирование',
        'Сопровождение проектов',
        'Авторский надзор',
        'Управление строительством',
        'Технический заказчик',
        'Финансовый аудит',
        'Сметное дело',
      ],
      mockDescription: 'Описание услуги будет сгенерировано AI, когда API ключ будет доступен. Это пример текста.',
      error: 'API ключ не настроен. Отображаются демонстрационные данные.',
    },
    footer: {
      copyright: '© {year} v-grand. Все права защищены.',
      privacy: 'Политика конфиденциальности',
      terms: 'Условия использования',
      email: 'info@v-grand.com',
    },
  },
  en: {
    title: 'Engineering Company',
    header: {
      services: 'Services',
      contact: 'Contact Us',
    },
    nav: [
      { name: 'Home', href: '#' },
      { name: 'About Us', href: '#' },
      { name: 'Blog / Cases', href: '#' },
    ],
    hero: {
      title: 'Comprehensive Engineering and Design',
      subtitle: 'We provide a full range of services: from concept development to author\'s supervision and project commissioning.',
      button: 'Start a Project',
    },
    services: {
      sectionTitle: 'Our Services',
      title: 'Full Cycle of Engineering Services',
      subtitle: 'We offer comprehensive solutions for all stages of your project implementation.',
      serviceNames: [
        'Engineering',
        'Design',
        'Project Support',
        'Author\'s Supervision',
        'Construction Management',
        'Technical Customer',
        'Financial Audit',
        'Cost Estimating',
      ],
      mockDescription: 'Service description will be generated by AI when the API key is available. This is a sample text.',
      error: 'API key is not configured. Demo data is displayed.',
    },
    footer: {
      copyright: '© {year} v-grand. All rights reserved.',
      privacy: 'Privacy Policy',
      terms: 'Terms of Use',
      email: 'info@v-grand.com',
    },
  },
};
